import{a as L,S as w,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const v="50807902-002d645a27b80276fb895a01b",S="https://pixabay.com/api/";async function u(o,r=1,e=15){const i={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e};return(await L.get(S,{params:i})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let q=new w(".gallery a");function p(o){const r=o.map(e=>`
        <li class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b> ${e.likes}</p>
            <p class="info-item"><b>Views</b> ${e.views}</p>
            <p class="info-item"><b>Comments</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",r),q.refresh()}function B(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function E(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}let l="",s=1,d=0;const R=document.querySelector("#search-form"),$=document.querySelector(".load-more");R.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.searchQuery.value.trim();if(r){l=r,s=1,B(),b(),g();try{const e=await u(l,s);if(d=e.totalHits,e.hits.length===0){a.info({title:"Info",message:"Sorry, no images found. Try again.",position:"topRight"});return}p(e.hits),d>15&&E()}catch{a.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}}});$.addEventListener("click",async()=>{s+=1,g();try{const o=await u(l,s);p(o.hits),I(),(s-1)*15+o.hits.length>=d&&(b(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}});function I(){const{height:o}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
