import{a as v,S as E,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const R="50807902-002d645a27b80276fb895a01b",S="https://pixabay.com/api/";async function f(o,r=1,e=15){const l={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:e};return(await v.get(S,{params:l})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more");let q=new E(".gallery a");function g(o){const r=o.map(e=>`
        <li class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b> ${e.likes}</p>
            <p class="info-item"><b>Views</b> ${e.views}</p>
            <p class="info-item"><b>Comments</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){p.innerHTML=""}function y(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function b(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}const n=15;let d="",a=1,u=0;const $=document.querySelector("#search-form"),B=document.querySelector(".load-more");$.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.searchQuery.value.trim();if(!r){i.warning({title:"Увага",message:"Поле пошуку не може бути порожнім.",position:"topRight"});return}d=r,a=1,P(),w(),y();try{const e=await f(d,a,n);if(u=e.totalHits,e.hits.length===0){i.info({title:"Info",message:"На жаль, зображень не знайдено. Спробуйте інший запит.",position:"topRight"});return}g(e.hits),u<=n||e.hits.length<n?i.info({title:"End",message:`Це всі результати за запитом (показано ${e.hits.length}).`,position:"topRight"}):b()}catch{i.error({title:"Error",message:"Щось пішло не так!",position:"topRight"})}finally{L()}});B.addEventListener("click",async()=>{a+=1,w(),y();try{const o=await f(d,a,n);g(o.hits),M();const r=(a-1)*n+o.hits.length;o.hits.length<n||r>=u?i.info({title:"End",message:"Це всі результати за запитом.",position:"topRight"}):b()}catch{i.error({title:"Error",message:"Щось пішло не так!",position:"topRight"})}finally{L()}});function M(){const{height:o}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
